version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: "164829817152"
    AWS_DEFAULT_REGION: "eu-west-3"
    IMAGE_REPO_NAME: "etl-finance-repo" 
    IMAGE_TAG: "latest" 
    
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ECR_LOGIN_COMMAND=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - echo $ECR_LOGIN_COMMAND | docker login --username AWS --password-stdin $ECR_URI
      - IMAGE_URI=$ECR_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
  
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_URI
      
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $IMAGE_URI
      - echo "Build succeeded for image $IMAGE_URI"
